In [ ]:
#Task 1

class PlayerEarning:

  def __init__(self, name):
    self.name = name

  def calculateTotal(self, earn, goals = None):
    self.earnings = earn
    self.bonus = 0
    if goals != None:
      if goals > 30:
        self.bonus = int((5 / 100) * self.earnings + 10000)
      else:
        self.bonus = int((5 / 100) * self.earnings)
    else:
      self.bonus = 0
    self.total = self.earnings + self.bonus

  def printDetails(self):
    print(f'''Player Name: {self.name}
Player Season Earning without bonus: {self.earnings}
Bonus: {self.bonus}
Player Season Earning After Bonus: {self.total}''')

#Write till here


print("**********************")
player1 = PlayerEarning('Buffon')
player1.calculateTotal(250000)
player1.printDetails()

print("\n**********************")
player2 = PlayerEarning('Dybala')
player2.calculateTotal(250000, 31)
player2.printDetails()

print("\n**********************")
player3 = PlayerEarning('Cuadrado')
player3.calculateTotal(250000, 20)
player3.printDetails()

**********************
Player Name: Buffon
Player Season Earning without bonus: 250000
Bonus: 0
Player Season Earning After Bonus: 250000

**********************
Player Name: Dybala
Player Season Earning without bonus: 250000
Bonus: 22500
Player Season Earning After Bonus: 272500

**********************
Player Name: Cuadrado
Player Season Earning without bonus: 250000
Bonus: 12500
Player Season Earning After Bonus: 262500

In [ ]:
#Task 2

class myList:

  def __init__(self, *args):
    self.list1 = []
    for iter1 in args:
      self.list1.append(iter1)
  
  def sum(self):
    if len(self.list1) == 0:
      print("Sum:", 0)
    else:
      print("Sum:", sum(self.list1))
  
  def merge(self, *args):
    for iter2 in args:
      self.list1.append(iter2)
  
  def average(self):
    if len(self.list1) == 0:
      print("Average:", 0)
    else:
      print("Average:", sum(self.list1) / len(self.list1))

#Write till here


l1 =  myList(2,3,4,5,6) #you might need a list inside your class to store the values
l1.sum()
l1.merge(4,5,9)
l1.sum()
l1.average()
print("-----------------------------")
l2 =  myList()
l2.average()
l2.merge(1,2,4,8)
l2.sum()

Sum: 20
Sum: 38
Average: 4.75
-----------------------------
Average: 0
Sum: 15

In [ ]:
#Task 3

class Bird:

  def __init__(self, name, flies = False, type1 = "N/S"):
    self.name = name
    self.flies = flies
    self.type1 = type1
  
  def fly(self):
    if self.flies == False:
      print(self.name, "can not fly")
    else:
      print(self.name, "can fly")

  def setType(self, type1):
    self.type1 = type1
  
  def printDetail(self):
    print("Name:", self.name)
    if self.type1 == "N/S":
      print("Type: Flightless Birds")
    else:
      print("Type:", self.type1)

#Write till here


ostrich = Bird('Ostrich')
duck = Bird("Duck", True)
owl = Bird('Owl', True)
print("###########################")
ostrich.fly()
duck.fly()
owl.fly()
duck.setType('Water Birds')
owl.setType('Birds of Prey')
print("=========================")
ostrich.printDetail()
print("=========================")
duck.printDetail()
print("=========================")
owl.printDetail()

###########################
Ostrich can not fly
Duck can fly
Owl can fly
=========================
Name: Ostrich
Type: Flightless Birds
=========================
Name: Duck
Type: Water Birds
=========================
Name: Owl
Type: Birds of Prey

In [ ]:
#Task 4

class Account:

  count = 0

  def __init__(self, name, age, occ, amount):
    self.name = name
    self.age = age
    self.occupation = occ
    self.amount = amount
    Account.count += 1
  
  def addMoney(self, amount):
    self.amount += amount

  def printDetails(self):
    print(f'''Name: {self.name}
Age: {self.age}
Occupation:  {self.occupation}
Total Amount:  {self.amount}''')
  
  def withdrawMoney(self, amount):
    if amount <= self.amount:
      self.amount -= amount
    else:
      pass

#Write till here


print('No of account holders:', Account.count)
print("=========================")
p1 = Account("Abdul", 45, "Service Holder", 500000)
p1.addMoney(300000)
p1.printDetails()
print("=========================")
p2 = Account("Rahim", 55, "Businessman", 700000)
p2.withdrawMoney(700000)
p2.printDetails()
print("=========================")
p3 = Account("Ashraf", 62, "Govt. Officer", 200000)
p3.withdrawMoney(250000)
p3.printDetails()
print("=========================") 
print('No of account holders:', Account.count)

No of account holders: 0
=========================
Name: Abdul
Age: 45
Occupation:  Service Holder
Total Amount:  800000
=========================
Name: Rahim
Age: 55
Occupation:  Businessman
Total Amount:  0
=========================
Name: Ashraf
Age: 62
Occupation:  Govt. Officer
Total Amount:  200000
=========================
No of account holders: 3

In [ ]:
#Task 5

class Smartphone:

  def __init__(self, name = None):
    self.name = name
    self.dict1 = {}

  def addFeature(self, feature, size):
    if self.name == None:
      print("Feature can not be added without phone name")
    else:
      if feature not in self.dict1:
        self.dict1[feature] = size
      else:
        self.dict1[feature] += ", " + size

  def printDetail(self):
    print("Phone Name:", self.name)
    for key, value in self.dict1.items():
      print(key + ":", value)
  
  def setName(self, name):
    self.name = name

#Write till here


s1 = Smartphone()
print("=================================")
s1.addFeature("Display", "6.1 inch")
print("=================================")
s1.setName("Samsung Note 20")
s1.addFeature("Display", "6.1 inch")
s1.printDetail()
print("=================================")
s2 = Smartphone("Iphone 12 Pro")
s2.addFeature("Display", "6.2 inch")
s2.addFeature("Ram", "6 GB")
print("=================================")
s2.printDetail()
s2.addFeature("Display", "Amoled panel")
s2.addFeature("Ram", "DDR5")
print("=================================")
s2.printDetail()
print("=================================")

=================================
Feature can not be added without phone name
=================================
Phone Name: Samsung Note 20
Display: 6.1 inch
=================================
=================================
Phone Name: Iphone 12 Pro
Display: 6.2 inch
Ram: 6 GB
=================================
Phone Name: Iphone 12 Pro
Display: 6.2 inch, Amoled panel
Ram: 6 GB, DDR5
=================================

In [ ]:
#Task 6

class Student:

  count = 0
  cse = 0
  bba = 0

  def __init__(self, name, dept):
    Student.count += 1
    print("Creating Student Number:", Student.count)
    self.name = name
    self.dept = dept
    if dept == "CSE":
      Student.cse += 1
    else:
      Student.bba += 1


  def individualInfo(self):
    print(f'''{self.name} is from {self.dept} department.
Serial of {self.name} among all students' is: {self.count}
Serial of {self.name} in {self.dept} department is: ''', end = "")
    if self.dept == "CSE":
      print(Student.cse)
    else:
      print(Student.bba)
  
  def totalInfo(self):
    print(f'''Total Number of Student: {Student.count}
Total Number of CSE Student: {Student.cse}
Total Number of BBA Student: {Student.bba}''')

#Write till here


s1 = Student("Naruto", "CSE")
print('----------------------')
s1.individualInfo()
print('#############################')
s1.totalInfo()
print('============================')
 
s2 = Student("Sakura", "BBA")
print('----------------------')
s2.individualInfo()
print('#############################')
s2.totalInfo()
print('============================')
 
s3 = Student("Shikamaru", "CSE")
print('----------------------')
s3.individualInfo()
print('#############################')
s3.totalInfo()
print('============================')
 
s4 = Student("Deidara", "BBA")
print('----------------------')
s4.individualInfo()
print('#############################')
s4.totalInfo()

Creating Student Number: 1
----------------------
Naruto is from CSE department.
Serial of Naruto among all students' is: 1
Serial of Naruto in CSE department is: 1
#############################
Total Number of Student: 1
Total Number of CSE Student: 1
Total Number of BBA Student: 0
============================
Creating Student Number: 2
----------------------
Sakura is from BBA department.
Serial of Sakura among all students' is: 2
Serial of Sakura in BBA department is: 1
#############################
Total Number of Student: 2
Total Number of CSE Student: 1
Total Number of BBA Student: 1
============================
Creating Student Number: 3
----------------------
Shikamaru is from CSE department.
Serial of Shikamaru among all students' is: 3
Serial of Shikamaru in CSE department is: 2
#############################
Total Number of Student: 3
Total Number of CSE Student: 2
Total Number of BBA Student: 1
============================
Creating Student Number: 4
----------------------
Deidara is from BBA department.
Serial of Deidara among all students' is: 4
Serial of Deidara in BBA department is: 2
#############################
Total Number of Student: 4
Total Number of CSE Student: 2
Total Number of BBA Student: 2

In [ ]:
#Task 7

class book:
    def __init__(self, name):
        self.name = name
        self.genre='biography'
    def review(self):
         print('This book is just out of the world,mind-blowing!')

# Write from here

class fiction(book):

  def __init__(self, name, gen):
    super().__init__(name)
    self.genre = gen
  
  def review(self):
    print(f"{self.name} which is a {self.genre} is just out of the world, mind-blowing!")

class nonfiction(book):

  def review(self):
    print(f"{self.name} which is a {self.genre} is just out of the world, mind-blowing!")
  
#Write till here


b1 = fiction('The Shining','Psychological horror')
b2 = nonfiction('A Beautiful Mind')
b1.review()
print('=========================')
b2.review()
print('=========================')

The Shining which is a Psychological horror is just out of the world, mind-blowing!
=========================
A Beautiful Mind which is a biography is just out of the world, mind-blowing!
=========================

In [ ]:
#Task 8

class Processor:
    def __init__(self, model, thread, core):
        self.model = model
        self.core = core
        self.thread = thread
    def getInfo(self):
        return "Model:"+self.model+ "\nCores:"+str(self.core)+ "\nThreads:"+ str(self.thread) 

# Write from here

class Intel(Processor):

  def __init__(self, model, core, thread, price):
    super().__init__(model, thread, core)
    self.price = price
  
  def getInfo(self):
    print(f'''{super().getInfo()}
Price: {self.price}taka''')
    
class AMD(Processor):

  def __init__(self, model, core, thread, price):
    super().__init__(model, thread, core)
    self.price = price
  
  def getInfo(self):
    print(f'''{super().getInfo()}
Price: {self.price}taka''')

#Write till here

      
p1 = Intel("Intel i5 10th Gen",6,12,17000)
p2 = AMD("Ryzen 5 3500X",6,6,13800)
p3 = AMD("Ryzen 5 3600",6,12,16900)
print('======================')
p1.getInfo()
print('======================')
p2.getInfo()
print('======================')
p3.getInfo()

======================
Model:Intel i5 10th Gen
Cores:6
Threads:12
Price: 17000taka
======================
Model:Ryzen 5 3500X
Cores:6
Threads:6
Price: 13800taka
======================
Model:Ryzen 5 3600
Cores:6
Threads:12
Price: 16900taka

In [ ]:
#Task 9

class Fruit:
    Total_order=0
    
    def __init__(self, Order_ID, weight):
        self.Order_ID=Order_ID
        self.weight=weight
        Fruit.Total_order=Fruit.Total_order+1
    
    def __str__(self):
        return self.Order_ID+", Weight: "+str(self.weight)

class Mango(Fruit):

    #Write from here

    def __init__(self, id, weight, var, pri):
        super().__init__(id, weight)
        self.variety = var
        self.total = self.weight * pri

    def __str__(self):
        return f'''{super().__str__()}, Variety: {self.variety},
Total Price: {self.total}'''

    def __add__(self, obj):
      return f"The total Price of the orders are: {self.total + obj.total}"

    #Write till here


class JackFruit(Fruit):

    #Write from here

    def __init__(self, id, weight, pri):
        super().__init__(id, weight)
        self.total = self.weight * pri

    def __str__(self):
        return f'''{super().__str__()}, Total Price: {self.total}'''

    def __add__(self, obj):
      return f"The total Price of the orders are: {self.total + obj.total}"

    #Write till here
    

m1=Mango("Order Id 1", 5,"GopalVog",250)
print(m1)
m2=Mango("Order Id 2", 5,"HariVanga", 230)
print(m2) 
j1=JackFruit("Order Id 3", 5,250)
print(j1)
j2=JackFruit("Order Id 4", 4,210)
print(j2)
print("Total number of Orders: "+str(Fruit.Total_order))
print("==================")
print(m1+m2)
print("==================")
print(j1+j2)

Order Id 1, Weight: 5, Variety: GopalVog,
Total Price: 1250
Order Id 2, Weight: 5, Variety: HariVanga,
Total Price: 1150
Order Id 3, Weight: 5, Total Price: 1250
Order Id 4, Weight: 4, Total Price: 840
Total number of Orders: 4
==================
The total Price of the orders are: 2400
==================
The total Price of the orders are: 2090

In [ ]:
#Task 10

class Student:
    def __init__(self,name,ID):
        self.name = name
        self.ID = ID
    def Details(self):
        return "Name: "+self.name+"\n"+"ID: "+self.ID+"\n"

#Write from here

class CSEStudent(Student):

  def __init__(self, name, id, sem):
    super().__init__(name, id)
    self.semester = sem
  
  def Details(self):
    return f'''{super().Details()}Current semester: {self.semester}'''

  def addCourseWithMarks(self, *args):
    self.crs_gr = args

  def showGPA(self):
    print(f"{self.name} has taken {len(self.crs_gr) // 2} courses.")
    sum = 0
    for iter in range(len(self.crs_gr)):
      if iter % 2 == 0:
        print(self.crs_gr[iter], end = ": ")
      else:
        if self.crs_gr[iter] >= 85:
          grade =4.0
        elif 84 >= self.crs_gr[iter] >= 80:
          grade = 3.3
        elif 79 >= self.crs_gr[iter] >= 70:
          grade = 3.0
        elif 69 >= self.crs_gr[iter] >= 65:
          grade = 2.3
        elif 64 >= self.crs_gr[iter] >= 57:
          grade = 2.0
        elif 56 >= self.crs_gr[iter] >= 55:
          grade = 1.3
        elif 54 >= self.crs_gr[iter] >= 50:
          grade = 1.0
        else:
          grade = 0.0
        print(grade)
        sum += grade
    gpa = sum * 3/ (len(self.crs_gr) // 2 * 3)
    print(f"GPA of {self.name} is: {'{0:4.2f}'.format(gpa)}")

#Write till here


Bob = CSEStudent("Bob","20301018","Fall 2020")
Carol = CSEStudent("Carol","16301814","Fall 2020")
Anny = CSEStudent("Anny","18201234","Fall 2020")
print("#########################")
print(Bob.Details())
print("#########################")
print(Carol.Details())
print("#########################")
print(Anny.Details())
print("#########################")
Bob.addCourseWithMarks("CSE111",83.5,"CSE230",73.0,"CSE260",92.5)
Carol.addCourseWithMarks("CSE470",62.5,"CSE422",69.0,"CSE460",76.5,"CSE461",87.0)
Anny.addCourseWithMarks("CSE340",45.5,"CSE321",95.0,"CSE370",91.0)
print("----------------------------")
Bob.showGPA()
print("----------------------------")
Carol.showGPA()
print("----------------------------")
Anny.showGPA()

#########################
Name: Bob
ID: 20301018
Current semester: Fall 2020
#########################
Name: Carol
ID: 16301814
Current semester: Fall 2020
#########################
Name: Anny
ID: 18201234
Current semester: Fall 2020
#########################
----------------------------
Bob has taken 3 courses.
CSE111: 3.3
CSE230: 3.0
CSE260: 4.0
GPA of Bob is: 3.43
----------------------------
Carol has taken 4 courses.
CSE470: 2.0
CSE422: 2.3
CSE460: 3.0
CSE461: 4.0
GPA of Carol is: 2.83
----------------------------
Anny has taken 3 courses.
CSE340: 0.0
CSE321: 4.0
CSE370: 4.0
GPA of Anny is: 2.67

In [ ]:
#Task 11

class Transport:
    total_traveller = 0
    
    def __init__(self, name, fare):
        self.name = name
        self.baseFare = fare
    
    def __str__(self):
        s =  "Name: "+self.name+", Base fare: "+str(self.baseFare)
        return s

# Write from here

class Bus(Transport):

  def __init__(self, name, fare):
    super().__init__(name, fare)
    print("Base-fare of", name, "is", fare, "Taka")

  def addPassengerWithBags(self, *args):
    self.info = args

  def __str__(self):
    string = f'''{super().__str__()}
Total Passenger(s): {len(self.info)//2}
Passenger details:'''
    add = 0
    for iter in range(len(self.info)):
      if iter % 2 == 0:
        string += "\nName: " + self.info[iter] + ", Fare: "
        Transport.total_traveller += 1
      else:
        if 3 <= self.info[iter] <= 5:
          add = 60
        elif self.info[iter] > 5:
          add = 105
        else:
          add = 0
        string += str(self.baseFare + add)
    return string

class Train(Transport):

  def __init__(self, name, fare):
    super().__init__(name, fare)
    print("Base-fare of", name, "is", fare, "Taka")

  def addPassengerWithBags(self, *args):
    self.info = args

  def __str__(self):
    string = f'''{super().__str__()}
Total Passenger(s): {len(self.info)//2}
Passenger details:'''
    add = 0
    for iter in range(len(self.info)):
      if iter % 2 == 0:
        string += "\nName: " + self.info[iter] + ", Fare: "
        Transport.total_traveller += 1
      else:
        if 3 <= self.info[iter] <= 5:
          add = 60
        elif self.info[iter] > 5:
          add = 105
        else:
          add = 0
        string += str(self.baseFare + add)
    return string

# Write till here


t1 = Bus("Volvo", 950)
print("=================================")
t1.addPassengerWithBags("David", 6,  "Mike", 1, "Carol", 3)
print("=================================")
print(t1)
print("=================================")
t2 = Train("Silk City", 850)
print("=================================")
t2.addPassengerWithBags("Bob", 2, "Simon", 4)
print("=================================")
print(t2)
print("=================================")
print("Total Passengers in Transport: ", Transport.total_traveller )

Base-fare of Volvo is 950 Taka
=================================
=================================
Name: Volvo, Base fare: 950
Total Passenger(s): 3
Passenger details:
Name: David, Fare: 1055
Name: Mike, Fare: 950
Name: Carol, Fare: 1010
=================================
Base-fare of Silk City is 850 Taka
=================================
=================================
Name: Silk City, Base fare: 850
Total Passenger(s): 2
Passenger details:
Name: Bob, Fare: 850
Name: Simon, Fare: 910
=================================
Total Passengers in Transport:  5

In [ ]:
#Task 12

class AppleProduct:
  def __init__(self, name, model, base_price):
    self.name = name
    self.model = model
    self.base_price = base_price
  def companyInfo(self):
    st = ("Company Name: Apple\nFouder: Steve Jobs, Steve Wozniak, Ronald Wayne\nCurrent CEO: Tim Cook\nAddress: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States")    
    return st
  def feature(self):
    st = (f"Name: {self.name}\nProduct Model: {self.model}\nHardware Quality: Excellent Hardwares\nGuarantee/ Warranty: Apple Care")
    return st
  def __str__(self):
    print('This is apple product.')
  def calculatePrice(self):
    print('Total Price:', self.base_price)

# Write from here

class MacBookPro2020(AppleProduct):

  def __init__(self, name, model, ram, chip, rateT):
    super().__init__(name, model, 1299)
    self.ram = ram
    self.chip = chip
    self.rateT = rateT
  
  def __str__(self):
    return f'''Product Details:
Name: {self.name}
Product Model: {self.model}
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
RAM: {self.ram}GB
Chip: {self.chip}
Company Details:
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States'''

  def calculatePrice(self):
    tax = (self.base_price * self.rateT) / 100
    self.total = self.base_price + tax
    print(f'''Calculating Total Price:
Base Price: {self.base_price}
Tax: {self.rateT}%
Total Price: {self.total}''')
    
  def __add__(self, obj):
    return self.total + obj.total
    
class iPhone12(AppleProduct):

  def __init__(self, name, model, ram, chip, rateT):
    super().__init__(name, model, 799)
    self.ram = ram
    self.chip = chip
    self.rateT = rateT
  
  def __str__(self):
    return f'''Product Details:
Name: {self.name}
Product Model: {self.model}
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
RAM: {self.ram}GB
Chip: {self.chip}
Company Details:
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States'''

  def calculatePrice(self):
    tax = (self.base_price * self.rateT) / 100
    self.total = self.base_price + tax
    print(f'''Calculating Total Price:
Base Price: {self.base_price}
Tax: {self.rateT}%
Total Price: {self.total}''')

# Write till here


m1 = MacBookPro2020('MacBook', 'MacBookPro2020', 8, 'M1', 10)
print(m1)
print('====================================')
m1.calculatePrice()
print('###################################')
iphone = iPhone12('iPhone', 'iPhone 12', 8, 'A14', 5)
print(iphone)
print('====================================')
iphone.calculatePrice()  
print('###################################')
print('Total Price of these two products: ',end='')
print('%.2f Dollars'%(m1 + iphone))

Product Details:
Name: MacBook
Product Model: MacBookPro2020
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
RAM: 8GB
Chip: M1
Company Details:
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
====================================
Calculating Total Price:
Base Price: 1299
Tax: 10%
Total Price: 1428.9
###################################
Product Details:
Name: iPhone
Product Model: iPhone 12
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
RAM: 8GB
Chip: A14
Company Details:
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
====================================
Calculating Total Price:
Base Price: 799
Tax: 5%
Total Price: 838.95
###################################
Total Price of these two products: 2267.85 Dollars

In [ ]:
#Task 13

class University:
  name  = "ABC University"
  numberOfStudents = 0
  admissionFee = 28000
  Library = 2000
  def __init__(self, n,i):
    self.stName = n
    self.stId = i
          
  def payment(self):
    return self.admissionFee + self.Library
  
  def __str__(self):
    return "Student Name: {}, ID: {}\nFee: {}".format(self.stName, self.stId, self.payment())
 
# Write from here

class CSE_dept(University):

  PerCreditFee = 6600
  SemesterFee = 7700
  LabFee = 2750

  def __init__(self, name, id, cred = 6):
    super().__init__(name, id)
    University.numberOfStudents += 1
    self.credits = cred

  def payment(self):
    return super().payment() + CSE_dept.SemesterFee + CSE_dept.PerCreditFee * self.credits + CSE_dept.LabFee

  def payment_details(self):
    print(f'''DETAILS:
Admission Fee: {University.admissionFee}
Library Fee: {University.Library}
Semester Fee: {CSE_dept.SemesterFee}
Per Credit Fee: {CSE_dept.PerCreditFee}
Number of credits: {self.credits}
Lab Fee: {CSE_dept.LabFee}''')
  
  def __add__(self, obj):
    return self.payment() + obj.payment()

class PHR_dept(University):

  PerCreditFee = 6600
  SemesterFee = 11000

  def __init__(self, name, id, cred = 9):
    super().__init__(name, id)
    University.numberOfStudents += 1
    self.credits = cred

  def payment_details(self):
    print(f'''DETAILS:
Admission Fee: {University.admissionFee}
Library Fee: {University.Library}
Semester Fee: {PHR_dept.SemesterFee}
Per Credit Fee: {PHR_dept.PerCreditFee}
Number of credits: {self.credits}''')
    
  def __add__(self, obj):
    return self.payment() + obj.payment()

  def payment(self):
    return super().payment() + PHR_dept.SemesterFee + PHR_dept.PerCreditFee * self.credits

# Write till here


c1 = CSE_dept("Mary","5678")  
print(c1)
c1.payment_details()
print("===========================")
p1 = PHR_dept("Simon","91011")  
print(p1)
p1.payment_details()
print("===========================")
c2 = CSE_dept("Adam","1234", 12)  
print(c2)
c2.payment_details()
print("===========================")
p2 = PHR_dept("David","121314", 15)  
print(p2)
p2.payment_details()
print("===========================")
print("Total Number of Students:", University.numberOfStudents)
print("Total University Revenue:", (c1 + c2) + (p1 + p2))
print("===========================")
print("Due to the pandemic, admission and library fees have been reduced for all departments. ")
University.admissionFee -= 1000
University.Library -= 100
print("The credit, semester and lab fees have been reduced for the CSE department. ")
CSE_dept.PerCreditFee -= 100
CSE_dept.SemesterFee -= 100
CSE_dept.LabFee -=100
print("The credit and semester fees have been reduced for the PHR department.\n ")
PHR_dept.PerCreditFee -= 100
PHR_dept.SemesterFee -= 1000
print(c1)
print(p1)
print(c2)
print(p2)
print("===========================")
print("Total Number of Students:", University.numberOfStudents)
print("Total University Revenue:", (c1 + c2) + (p1 + p2))

Student Name: Mary, ID: 5678
Fee: 80050
DETAILS:
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 7700
Per Credit Fee: 6600
Number of credits: 6
Lab Fee: 2750
===========================
Student Name: Simon, ID: 91011
Fee: 100400
DETAILS:
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 11000
Per Credit Fee: 6600
Number of credits: 9
===========================
Student Name: Adam, ID: 1234
Fee: 119650
DETAILS:
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 7700
Per Credit Fee: 6600
Number of credits: 12
Lab Fee: 2750
===========================
Student Name: David, ID: 121314
Fee: 140000
DETAILS:
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 11000
Per Credit Fee: 6600
Number of credits: 15
===========================
Total Number of Students: 4
Total University Revenue: 440100
===========================
Due to the pandemic, admission and library fees have been reduced for all departments.
The credit, semester and lab fees have been reduced for the CSE department.
The credit and semester fees have been reduced for the PHR department.

Student Name: Mary, ID: 5678
Fee: 78150
Student Name: Simon, ID: 91011
Fee: 97400
Student Name: Adam, ID: 1234
Fee: 117150
Student Name: David, ID: 121314
Fee: 136400
===========================
Total Number of Students: 4
Total University Revenue: 429100

In [ ]:
#Task 14

class Library:
    Total_book = 1000
    borrow_data = {}
    
    def __init__(self,n,id):
        self.student_name = n
        self.student_id = id     
    
    def borrowbook(self):
        print("A book is borrowed!")
        
    def __str__(self):
        return "Library: XYZ"

#Write from here

class Student(Library):

  def borrowbook(self, book, id = None):
    if book not in Library.borrow_data:
      super().borrowbook()
      Library.borrow_data[book] = [self.student_name]
      Library.Total_book -= 1
      if id != None:
        print(f"'{book}' book with the unique id {id} is borrowed by {self.student_name}({self.student_id})")
      else:
        print(f"'{book}' book is borrowed by {self.student_name}({self.student_id})")
      print(f"Number of books available for borrowing = {Library.Total_book}")
    else:
      print(f"Sorry {self.student_name} ! {book} book is borrowed by {Library.borrow_data[book][0]}")

  def __str__(self):
    string = f'''{super().__str__()}
Student Name: {self.student_name} ID: {self.student_id}
Books borrowed: '''
    for key, val in Library.borrow_data.items():
      if self.student_name in val:
        string += key + ", "
  
    return string[:-2]

  def returnAllBooks(self):
    temp = Library.borrow_data.copy()
    for key, val in temp.items():
      if self.student_name in val:
        Library.borrow_data.pop(key)
        Library.Total_book += 1
    print("All Books are returned by", self.student_name + ".")
    

#Write till here


s1 = Student("Alice",18101259)
s1.borrowbook("The Alchemist", "Hdw652")
print("===============")
print(s1)
print("===============")
print(Library.borrow_data)
print("===============")
s1.borrowbook("Wuthering Heights")
print("===============")
print(s1)
print("===============")
s2= Student("David",18141777)
s2.borrowbook("The Alchemist", "Hdw652")
print("===============")
s2.borrowbook("The Vampyre")
print("===============")
print(Library.borrow_data)
print("===============")
s1.returnAllBooks()
print("===============")
print(Library.borrow_data)

A book is borrowed!
'The Alchemist' book with the unique id Hdw652 is borrowed by Alice(18101259)
Number of books available for borrowing = 999
===============
Library: XYZ
Student Name: Alice ID: 18101259
Books borrowed: The Alchemist
===============
{'The Alchemist': ['Alice']}
===============
A book is borrowed!
'Wuthering Heights' book is borrowed by Alice(18101259)
Number of books available for borrowing = 998
===============
Library: XYZ
Student Name: Alice ID: 18101259
Books borrowed: The Alchemist, Wuthering Heights
===============
Sorry David ! The Alchemist book is borrowed by Alice
===============
A book is borrowed!
'The Vampyre' book is borrowed by David(18141777)
Number of books available for borrowing = 997
===============
{'The Alchemist': ['Alice'], 'Wuthering Heights': ['Alice'], 'The Vampyre': ['David']}
===============
All Books are returned by Alice.
===============
{'The Vampyre': ['David']}

In [ ]:
#Task 15

class Player:
    database={}
    playerNo = 0
    def __init__(self,name,team,jerseyNo):
        self.name = name
        self.team = team
        self.jerseyNo = jerseyNo
    def __str__(self):
        return "Name:{}\nTeam:{}\nJersey No:{}".format(self.name,self.team,self.jerseyNo)

#Write from here

class FootballPlayer(Player):

  def __init__(self, name, team, jerNo, goals, retired = "Not yet retired"):
    super().__init__(name, team, jerNo)
    self.goals = goals
    Player.playerNo += 1
    self.fn_ln = name.split(" ")
    self.retired = retired
    self.id = str(Player.playerNo) + self.fn_ln[0][0] + self.fn_ln[1][0] + str(self.jerseyNo)
    Player.database[self.id] = [name, team, jerNo, goals, retired]

  def __str__(self):
    string = f'''Player ID:{self.id}
{super().__str__()}
Goals Scored:{self.goals}
Retirement date:{self.retired}'''
    return string
  
  @classmethod
  def createPlayer(cls, name, team, jerNo, goals, retired):
    return cls(name, team, jerNo, goals, retired)

#Write till here


print("Number of players:",Player.playerNo)
print("Player Database:",Player.database)
print("#################################")
p1 = FootballPlayer("Lionel Messi","Barcelona",10,231)
print("------Details of the player------")
print(p1)
print("#################################")
p2 = FootballPlayer("Cristiano Ronaldo","Juventus",7,215)
print("------Details of the player------")
print(p2)
print("#################################")
p3 = FootballPlayer.createPlayer("Miroslav Klose","Lazio",11, 71,"11 Aug,2014")
print("------Details of the player------")
print(p3)
print("#################################")
print("Number of players:",Player.playerNo)
print("Player Database:",Player.database)

Number of players: 0
Player Database: {}
#################################
------Details of the player------
Player ID:1LM10
Name:Lionel Messi
Team:Barcelona
Jersey No:10
Goals Scored:231
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID:2CR7
Name:Cristiano Ronaldo
Team:Juventus
Jersey No:7
Goals Scored:215
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID:3MK11
Name:Miroslav Klose
Team:Lazio
Jersey No:11
Goals Scored:71
Retirement date:11 Aug,2014
#################################
Number of players: 3
Player Database: {'1LM10': ['Lionel Messi', 'Barcelona', 10, 231, 'Not yet retired'], '2CR7': ['Cristiano Ronaldo', 'Juventus', 7, 215, 'Not yet retired'], '3MK11': ['Miroslav Klose', 'Lazio', 11, 71, '11 Aug,2014']}